/* 
 * Forge SDK
 *
 * The Forge Platform contains an expanding collection of web service components that can be used with Autodesk cloud-based products or your own technologies. Take advantage of Autodesk’s expertise in design and engineering.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: forge.help@autodesk.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Autodesk.Forge;
using Autodesk.Forge.Model;
using Autodesk.Forge.Client;
using System.Reflection;

namespace Autodesk.Forge.Test
{
    /// <summary>
    ///  Class for testing BucketsItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BucketsItemsTests
    {
        // TODO uncomment below to declare an instance variable for BucketsItems
        //private BucketsItems instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BucketsItems
            //instance = new BucketsItems();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BucketsItems
        /// </summary>
        [Test]
        public void BucketsItemsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BucketsItems
            //Assert.IsInstanceOfType<BucketsItems> (instance, "variable 'instance' is a BucketsItems");
        }

        /// <summary>
        /// Test the property 'BucketKey'
        /// </summary>
        [Test]
        public void BucketKeyTest()
        {
            // TODO unit test for the property 'BucketKey'
        }
        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [Test]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }
        /// <summary>
        /// Test the property 'PolicyKey'
        /// </summary>
        [Test]
        public void PolicyKeyTest()
        {
            // TODO unit test for the property 'PolicyKey'
        }

    }

}
