/* 
 * Forge SDK
 *
 * The Forge Platform contains an expanding collection of web service components that can be used with Autodesk cloud-based products or your own technologies. Take advantage of Autodesk’s expertise in design and engineering.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: forge.help@autodesk.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Autodesk.Forge;
using Autodesk.Forge.Model;
using Autodesk.Forge.Client;
using System.Reflection;

namespace Autodesk.Forge.Test
{
    /// <summary>
    ///  Class for testing ObjectDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ObjectDetailsTests
    {
        // TODO uncomment below to declare an instance variable for ObjectDetails
        //private ObjectDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ObjectDetails
            //instance = new ObjectDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ObjectDetails
        /// </summary>
        [Test]
        public void ObjectDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ObjectDetails
            //Assert.IsInstanceOfType<ObjectDetails> (instance, "variable 'instance' is a ObjectDetails");
        }

        /// <summary>
        /// Test the property 'BucketKey'
        /// </summary>
        [Test]
        public void BucketKeyTest()
        {
            // TODO unit test for the property 'BucketKey'
        }
        /// <summary>
        /// Test the property 'ObjectId'
        /// </summary>
        [Test]
        public void ObjectIdTest()
        {
            // TODO unit test for the property 'ObjectId'
        }
        /// <summary>
        /// Test the property 'ObjectKey'
        /// </summary>
        [Test]
        public void ObjectKeyTest()
        {
            // TODO unit test for the property 'ObjectKey'
        }
        /// <summary>
        /// Test the property 'Sha1'
        /// </summary>
        [Test]
        public void Sha1Test()
        {
            // TODO unit test for the property 'Sha1'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Test]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'ContentType'
        /// </summary>
        [Test]
        public void ContentTypeTest()
        {
            // TODO unit test for the property 'ContentType'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Test]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }

    }

}
