/* 
 * Forge SDK
 *
 * The Forge Platform contains an expanding collection of web service components that can be used with Autodesk cloud-based products or your own technologies. Take advantage of Autodesk’s expertise in design and engineering.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: forge.help@autodesk.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Autodesk.Forge;
using Autodesk.Forge.Model;
using Autodesk.Forge.Client;
using System.Reflection;

namespace Autodesk.Forge.Test
{
    /// <summary>
    ///  Class for testing RelRefMeta
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RelRefMetaTests
    {
        // TODO uncomment below to declare an instance variable for RelRefMeta
        //private RelRefMeta instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RelRefMeta
            //instance = new RelRefMeta();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RelRefMeta
        /// </summary>
        [Test]
        public void RelRefMetaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RelRefMeta
            //Assert.IsInstanceOfType<RelRefMeta> (instance, "variable 'instance' is a RelRefMeta");
        }

        /// <summary>
        /// Test the property 'RefType'
        /// </summary>
        [Test]
        public void RefTypeTest()
        {
            // TODO unit test for the property 'RefType'
        }
        /// <summary>
        /// Test the property 'Direction'
        /// </summary>
        [Test]
        public void DirectionTest()
        {
            // TODO unit test for the property 'Direction'
        }
        /// <summary>
        /// Test the property 'FromId'
        /// </summary>
        [Test]
        public void FromIdTest()
        {
            // TODO unit test for the property 'FromId'
        }
        /// <summary>
        /// Test the property 'FromType'
        /// </summary>
        [Test]
        public void FromTypeTest()
        {
            // TODO unit test for the property 'FromType'
        }
        /// <summary>
        /// Test the property 'ToId'
        /// </summary>
        [Test]
        public void ToIdTest()
        {
            // TODO unit test for the property 'ToId'
        }
        /// <summary>
        /// Test the property 'ToType'
        /// </summary>
        [Test]
        public void ToTypeTest()
        {
            // TODO unit test for the property 'ToType'
        }
        /// <summary>
        /// Test the property 'Extension'
        /// </summary>
        [Test]
        public void ExtensionTest()
        {
            // TODO unit test for the property 'Extension'
        }

    }

}
